version: '2'

services:
  stacksmithapi:
    tty: true
    image: 'stacksmith-py'
    ports: 
      - 8551:8551
    environment:
      - STACKSMITH_API_URL='https://stacksmith.bitnami.com/api/v1/'
      - STACKSMITH_NAMESPACE='beta-features'
      - STACKSMITH_AUTH_MACAROON=''
